### ISSUE TITLE
RFC: Rename idle() to update()

### ISSUE THREAD

**Issue by sanine-a** [scimusmn/arduino-base#11]
This is something that's bugged me for a bit, and I'd like to hear what others think. `idle()`, to me, suggests a NOP, whereas `update()` suggests, well, updating based on the present program or hardware state, which is what they actually do. For this reason, I personally would prefer to rename the `idle` functions as `update` functions.

**Comment by brandonwkipp** [comment]
I inherited `idle` from libraries members had already written. I personally think it would be ok to rename the functions, especially since the number of projects using this library is small.

**Comment by tnordberg** [comment]
I think that's a smart adjustment. `update` is more inclusive and common across several frameworks. 
E.g., it's totally fine to `idle` inside an update tick when there's nothing to do.
